### PR TITLE
WIP: Corrected multiple issues found during testing

### LINKED ISSUE #112: nodeSelector fails to validate
During testing of 0.0.8, it was found that specifying the `nodeSelector` failed to validate successfully.

According to those who performed the testing, the expected result was that the Quay ecosystem would deploy successfully. 

The observed behaviour was the following error:
```
The QuayEcosystem "quay-test-320" is invalid: []: Invalid value: map[string]interface {} : validation failure list:
spec.quay.nodeSelector in body must be of type object: "string"
```

Example CR:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    nodeSelector:
      role=node
```

It's possible that this may simply require a documentation enhancement if the `nodeSelector` was specified incorrectly.

### PR DESCRIPTION
**Pull request by sabre1041**
Resolves #112 #111 #110 #107 #106 #99

### CODE REVIEW

File: pkg/controller/quayecosystem/provisioning/provision.go [hunk 1]
```diff
@@ -475,7 +475,7 @@ func (r *ReconcileQuayEcosystemConfiguration) configurePostgreSQL(meta metav1.Ob
 
 	podName = postgresqlPodsItems[0].Name
 
-	success, stdout, stderr := k8sutils.ExecIntoPod(r.k8sclient, podName, fmt.Sprintf("echo \"SELECT * FROM pg_available_extensions\" | /opt/rh/rh-postgresql96/root/usr/bin/psql -d %s", r.quayConfiguration.QuayDatabase.Database), "", r.quayConfiguration.QuayEcosystem.Namespace)
+	success, stdout, stderr := k8sutils.ExecIntoPod(r.k8sclient, podName, fmt.Sprintf("echo \"SELECT * FROM pg_available_extensions\" | $(which psql) -d %s", r.quayConfiguration.QuayDatabase.Database), "", r.quayConfiguration.QuayEcosystem.Namespace)
```
Comment (kurtismullins) [inline pkg/controller/quayecosystem/provisioning/provision.go:478]: Nice!

**Review by kurtismullins — APPROVED** [review]
LGTM
